app_id = "app_01je8wrymzfetta5qxqpmfb7w6"

# This is where 'xtp plugin push' expects to find the wasm file after the build script has run.
bin = "dist/plugin.wasm"
extension_point_id = "ext_01je8xm8z7er8a0ax9dx48nvkg"
name = "filesystem"

[scripts]

  # xtp plugin build runs this script to generate the wasm file
  build = "tinygo build -target wasi -o dist/plugin.wasm ."

  # xtp plugin init runs this script to format the plugin code
  format = "go fmt"

  # xtp plugin init runs this script before running the format script
  prepare = "sh prepare.sh && go get ./..."
